[package]
name = "rustos-bootstrap-apps"
description = "Первые изолированные ELF64 процессы RustOS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "rustos-init"
path = "src/init.rs"

[[bin]]
name = "rustos-fault-test"
path = "src/fault_test.rs"

[[bin]]
name = "rustos-preempt-a"
path = "src/preempt_a.rs"

[[bin]]
name = "rustos-preempt-b"
path = "src/preempt_b.rs"

[[bin]]
name = "rustos-ipc-receiver"
path = "src/ipc_receiver.rs"

[[bin]]
name = "rustos-ipc-sender"
path = "src/ipc_sender.rs"

[[bin]]
name = "rustos-abi-lifecycle"
path = "src/abi_lifecycle.rs"

[[bin]]
name = "rustos-abi-child"
path = "src/abi_child.rs"

[[bin]]
name = "rustos-vfsd"
path = "src/vfsd.rs"

[[bin]]
name = "rustos-vfs-test"
path = "src/vfs_test.rs"

[[bin]]
name = "rustos-vfs-persistence"
path = "src/vfs_persistence.rs"

[[bin]]
name = "rustos-loader-test"
path = "src/loader_test.rs"

[[bin]]
name = "rustos-loader-child"
path = "src/loader_child.rs"

[[bin]]
name = "rustos-std-smoke"
path = "src/std_smoke.rs"
required-features = ["std-port"]

[features]
default = []
std-port = []

[dependencies]
rustos-abi = { path = "../../abi" }
rustos-runtime = { path = "../../runtime" }
rustos-vfs-client = { path = "../../libs/vfs" }
rustos-elf-loader = { path = "../../libs/elf-loader" }
varaniafs = { path = "../../varaniafs" }
