[package]
name = "rustos-crt"
description = "Минимальный startup runtime для обычных Rust-программ RustOS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustos-abi = { path = "../../abi" }
rustos-runtime = { path = "../../runtime" }
