[package]
name = "rustos-loader-root"
description = "ET_DYN root fixture with DT_NEEDED for fixture-1.dll"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
build = "build.rs"

[lib]
name = "loader_test_root"
path = "src/lib.rs"
crate-type = ["cdylib"]
